# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

jobs:
  - job: 'client'
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - task: Npm@1
        inputs:
          workingDir: client
          command: custom
          customCommand: install
        displayName: 'install'
      - task: Npm@1
        inputs:
          workingDir: client
          command: custom
          customCommand: run build
        displayName: 'build'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(System.DefaultWorkingDirectory)/client/dist'
          artifactName: 'client'
        displayName: 'publish'
  - job: 'server'
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - task: Npm@1
        inputs:
          workingDir: server
          command: custom
          customCommand: install
        displayName: 'install'
      - task: Npm@1
        inputs:
          workingDir: server
          command: custom
          customCommand: run build
        displayName: 'build'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(System.DefaultWorkingDirectory)/server/dist'
          artifactName: 'server'
        displayName: 'publish'
