# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

jobs:
  - job: 'client'
    pool:
      vmImage: 'win1803'
    steps:
      - task: Bash@1
        inputs:
          script: |
            npm i
            npm run build
        displayName: 'build'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(System.DefaultWorkingDirectory)/dist'
          artifactName: 'client'
        displayName: 'publish'
  - job: 'server'
    pool:
      vmImage: 'win1803'
    steps:
      - task: Bash@1
        inputs:
          script: |
            npm i
            npm run build
          workingDirectory: ./server
        displayName: 'build'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(System.DefaultWorkingDirectory)/server/dist'
          artifactName: 'server'
        displayName: 'publish'
